"""initial_migration

Revision ID: 253d98ad42f6
Revises: 152461a06b53
Create Date: 2024-11-26 00:57:52.771944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253d98ad42f6'
down_revision = '152461a06b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_teams', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('ranking_class', sa.String(), nullable=True),
    sa.Column('uniquetournament_name', sa.String(), nullable=False),
    sa.Column('uniquetournament_slug', sa.String(), nullable=False),
    sa.Column('uniquetournament_primary_color_hex', sa.String(), nullable=True),
    sa.Column('uniquetournament_secondary_color_hex', sa.String(), nullable=True),
    sa.Column('uniquetournament_category_name', sa.String(), nullable=True),
    sa.Column('uniquetournament_category_slug', sa.String(), nullable=True),
    sa.Column('uniquetournament_category_sport_name', sa.String(), nullable=True),
    sa.Column('uniquetournament_category_sport_slug', sa.String(), nullable=True),
    sa.Column('uniquetournament_category_sport_id', sa.Integer(), nullable=True),
    sa.Column('uniquetournament_category_id', sa.Integer(), nullable=True),
    sa.Column('uniquetournament_category_flag', sa.String(), nullable=True),
    sa.Column('uniquetournament_category_alpha2', sa.String(), nullable=True),
    sa.Column('uniquetournament_usercount', sa.Integer(), nullable=True),
    sa.Column('uniquetournament_id', sa.Integer(), nullable=False),
    sa.Column('uniquetournament_displayinversehomeawayteams', sa.Boolean(), nullable=False),
    sa.Column('country_alpha2', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_competitions')
    # ### end Alembic commands ###
