"""initial_migration

Revision ID: 9106082c669b
Revises: 253d98ad42f6
Create Date: 2024-11-26 01:33:57.034183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9106082c669b'
down_revision = '253d98ad42f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_competitions', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('uniquetournament_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('uniquetournament_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('uniquetournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('uniquetournament_displayinversehomeawayteams',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('country_alpha2',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('country_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_competitions', schema=None) as batch_op:
        batch_op.alter_column('country_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country_alpha2',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('uniquetournament_displayinversehomeawayteams',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('uniquetournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uniquetournament_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('uniquetournament_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
