"""Initial migration

Revision ID: bb0caa3e71b7
Revises: bc4dffa0d07d
Create Date: 2024-11-25 23:42:15.195057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0caa3e71b7'
down_revision = 'bc4dffa0d07d'
branch_labels = None
depends_on = None


def upgrade():
    print('ok')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_competitions', schema=None) as batch_op:
        
        batch_op.alter_column('country_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
     

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uniqueTournament_slug', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_flag', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rowName', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_sport_slug', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalTeams', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_alpha2', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rankingClass', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_slug', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_sport_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_sport_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_secondaryColorHex', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_primaryColorHex', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_userCount', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_category_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueTournament_displayInverseHomeAwayTeams', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('country_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('country_alpha2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('points',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('ranking',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
       #  batch_op.drop_column('unique_tournament_display_inverse_home_away_teams')
       #  batch_op.drop_column('unique_tournament_id')
       #  batch_op.drop_column('unique_tournament_user_count')
       #  batch_op.drop_column('unique_tournament_category_alpha2')
       #  batch_op.drop_column('unique_tournament_category_flag')
       #  batch_op.drop_column('unique_tournament_category_id')
       #  batch_op.drop_column('unique_tournament_category_sport_id')
       #  batch_op.drop_column('unique_tournament_category_sport_slug')
       #  batch_op.drop_column('unique_tournament_category_sport_name')
       #  batch_op.drop_column('unique_tournament_category_slug')
       #  batch_op.drop_column('unique_tournament_category_name')
       #  batch_op.drop_column('unique_tournament_secondary_color_hex')
       #  batch_op.drop_column('unique_tournament_primary_color_hex')
       #  batch_op.drop_column('unique_tournament_slug')
       #  batch_op.drop_column('unique_tournament_name')
       #  batch_op.drop_column('ranking_class')
       #  batch_op.drop_column('row_name')
       #  batch_op.drop_column('total_teams')

    # ### end Alembic commands ###
