version: '3.9'
services:
  web:
    image: flask-app:latest
    build: .
    ports:
      - "8080:8000"
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://miguelmagalhaes:yourpassword/miguelmagalhaes
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: miguelmagalhaes
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: miguelmagalhaes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
