name: Deploy Docker app to Google Cloud VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Action runs on Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

    - name: Configure Docker for Google Cloud
      run: |
        gcloud --quiet auth configure-docker

    - name: Build Docker image
      run: |
        docker-compose build

    - name: Add SSH key for Google Cloud
      run: |
        mkdir -p ~/.ssh  # Ensure the .ssh directory exists
        echo "${{ secrets.GCLOUD_SSH_KEY }}" | base64 -d > ~/.ssh/google_compute_engine
        chmod 600 ~/.ssh/google_compute_engine
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/google_compute_engine

    - name: Debug SSH Key
      run: |
        ls -l ~/.ssh/google_compute_engine
        file ~/.ssh/google_compute_engine

    - name: SSH into Google Cloud VM and deploy
      run: |
        gcloud compute ssh --zone "us-central1-b" "flask-app" --project "vertical-task-421920" --command '
          export GOOGLE_APPLICATION_CREDENTIALS="/home/miguelmagalhaes/gcp-sa-key.json"
          cd /home/miguelmagalhaes/flask_api_server
          docker-compose down
          docker-compose up -d
        '
