name: Deploy Docker app to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Use the secret stored in GitHub

    - name: Configure Docker for Google Cloud
      run: |
        gcloud --quiet auth configure-docker

    - name: Build Docker image
      run: |
        docker-compose build
        docker-compose push  # Optional: Push images to Docker Hub or GCR if needed

    - name: SSH into Google Cloud VM and deploy
      run: |
        gcloud compute ssh --zone "us-central1-b" "flask-app" --project "vertical-task-421920" << 'EOF'
          cd /path/to/your/app
          docker-compose down  # Stop any running containers
          docker-compose up -d  # Start the containers in detached mode
        EOF
